# -*- coding: utf-8 -*-
"""NERbert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qo_1Xov9XKdufAlAlpIaqXlhLUPyr56y
"""

import pandas as pd
data = pd.read_csv("Replica_NER.csv")

data.rename(columns={"sentence_id":"sentence_id","tokens":"words","tags":"labels"}, inplace =True)

data.head(10)

data = data.fillna(method = "ffill")

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data["sentence_id"] = LabelEncoder().fit_transform(data["sentence_id"] )

data["labels"] = data["labels"].str.upper()
data

X= data[["sentence_id","words"]]
Y =data["labels"]

x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size =0.2)

train_data = pd.DataFrame({"sentence_id":x_train["sentence_id"],"words":x_train["words"],"labels":y_train})
test_data = pd.DataFrame({"sentence_id":x_test["sentence_id"],"words":x_test["words"],"labels":y_test})

train_data

test_data

train_data.to_csv("train.csv", index=False)
test_data.to_csv("test.csv", index=False)

label = data["labels"].unique().tolist()
label

from simpletransformers.ner import NERModel,NERArgs

args = NERArgs()
args.num_train_epochs = 10
args.learning_rate = 1e-4
args.overwrite_output_dir =True
args.train_batch_size = 16
args.eval_batch_size = 16

model = NERModel('bert', "bert-base-multilingual-cased" ,labels=label, args =args, use_cuda=False)

model.train_model(train_data,eval_data = test_data,acc=accuracy_score)

result, model_outputs, preds_list = model.eval_model(test_data)

result

prediction, model_output = model.predict(["Олар Мексикаға кетті"])
prediction

prediction, model_output = model.predict(["Мен Алматыда тұрамын"])
prediction

prediction, model_output = model.predict(["Бауыржан Өзбекстанға пойызбен барады"])
prediction